export const LOAD_ANNOTATIONS = 'Ads/App/LOAD_ANNOTATIONS';
export const LOAD_ANNOTATIONS_SUCCESS = 'Ads/App/LOAD_ANNOTATIONS_SUCCESS';
export const LOAD_ANNOTATIONS_ERROR = 'Ads/App/LOAD_ANNOTATIONS_ERROR';
