/*
 *
 * ChartsPage constants
 *
 */

export const LOAD_ADS_STATS = 'app/ChartsPage/LOAD_ADS_STATS';
export const LOAD_ADS_STATS_SUCCESS = 'app/ChartsPage/LOAD_ADS_STATS_SUCCESS';
export const LOAD_ADS_STATS_ERROR = 'app/ChartsPage/LOAD_ADS_STATS_ERROR';

export const FB_ADS_REPORT_URL = 'https://www.facebook.com/ads/library/report/';

export const DEFAULT_EU_ELECTION_DATE = '2019-05-26';
export const EU_ELECTION_DATE_BY_COUNTRY = {
  AT: DEFAULT_EU_ELECTION_DATE,
  BE: DEFAULT_EU_ELECTION_DATE,
  BG: DEFAULT_EU_ELECTION_DATE,
  CY: DEFAULT_EU_ELECTION_DATE,
  CZ: '2019-05-25',
  DE: DEFAULT_EU_ELECTION_DATE,
  DK: DEFAULT_EU_ELECTION_DATE,
  EE: DEFAULT_EU_ELECTION_DATE,
  ES: DEFAULT_EU_ELECTION_DATE,
  FI: DEFAULT_EU_ELECTION_DATE,
  FR: DEFAULT_EU_ELECTION_DATE,
  GR: DEFAULT_EU_ELECTION_DATE,
  HR: DEFAULT_EU_ELECTION_DATE,
  HU: DEFAULT_EU_ELECTION_DATE,
  IE: '2019-05-24',
  IT: DEFAULT_EU_ELECTION_DATE,
  LT: DEFAULT_EU_ELECTION_DATE,
  LU: DEFAULT_EU_ELECTION_DATE,
  LV: '2019-05-25',
  MT: '2019-05-25',
  NL: '2019-05-23',
  PL: DEFAULT_EU_ELECTION_DATE,
  PT: DEFAULT_EU_ELECTION_DATE,
  RO: DEFAULT_EU_ELECTION_DATE,
  SI: DEFAULT_EU_ELECTION_DATE,
  SE: DEFAULT_EU_ELECTION_DATE,
  SK: '2019-05-25',
  GB: '2019-05-23',
};
